# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  GLAD_config = debug
  ImGui_config = debug
  DrawingPad_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  GLAD_config = release
  ImGui_config = release
  DrawingPad_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  GLAD_config = dist
  ImGui_config = dist
  DrawingPad_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW GLAD ImGui DrawingPad Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLAD GLFW ImGui

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C DrawingPad/vendor/glfw -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C DrawingPad/vendor/glad -f Makefile config=$(GLAD_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C DrawingPad/vendor/imgui -f Makefile config=$(ImGui_config)
endif

DrawingPad: GLFW GLAD ImGui
ifneq (,$(DrawingPad_config))
	@echo "==== Building DrawingPad ($(DrawingPad_config)) ===="
	@${MAKE} --no-print-directory -C DrawingPad -f Makefile config=$(DrawingPad_config)
endif

Sandbox: DrawingPad GLFW GLAD
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C DrawingPad/vendor/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C DrawingPad/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C DrawingPad/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C DrawingPad -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   ImGui"
	@echo "   DrawingPad"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"